### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'add_graph'

### ISSUE THREAD

**Issue by hittle2015** [jeffery0628/text_classification#11]
in file weibo_trainer.py 

line 116, in _valid_epoch
self.writer.writer.add_graph(input_model,[input_ids,mask_attentions, text_lengths])
AttributeError: 'NoneType' object has no attribute 'add_graph'

code output is as follows:
****************************************
loading features from cache file : htqe_data/.cache/htqe_train.cache...
loading features from cache file : htqe_data/.cache/htqe_valid.cache...
TextCNN1d(
  (embedding): Embedding(17707, 300)
  (convs): ModuleList(
    (0): Conv1d(300, 100, kernel_size=(3,), stride=(1,))
    (1): Conv1d(300, 100, kernel_size=(5,), stride=(1,))
    (2): Conv1d(300, 100, kernel_size=(7,), stride=(1,))
  )
  (fc): Linear(in_features=300, out_features=2, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
)
Trainable parameters: 450902
Train Epoch: 1 [0/47 (0%)] Loss: 0.699
Train Epoch: 1 [10/47 (21%)] Loss: 0.637
Train Epoch: 1 [20/47 (43%)] Loss: 0.684
Train Epoch: 1 [30/47 (64%)] Loss: 0.626
Train Epoch: 1 [40/47 (85%)] Loss: 0.680
Traceback (most recent call last):
  File "/home/david/Workspace/text_classification/train.py", line 65, in <module>
    run('configs/binary_classification/word_embedding_text_cnn_1d.yml')
  File "/home/david/Workspace/text_classification/train.py", line 60, in run
    main(config)
  File "/home/david/Workspace/text_classification/train.py", line 51, in main
    trainer.train()
  File "/home/david/Workspace/text_classification/base/base_trainer.py", line 82, in train
    result = self._train_epoch(epoch)
  File "/home/david/Workspace/text_classification/trainer/htqe_trainer.py", line 82, in _train_epoch
    val_log = self._valid_epoch(epoch)
  File "/home/david/Workspace/text_classification/trainer/htqe_trainer.py", line 116, in _valid_epoch
    self.writer.writer.add_graph(input_model,[input_ids,text_lengths])
AttributeError: 'NoneType' object has no attribute 'add_graph'
[Finished in 7.2s]

**Comment by hittle2015** [comment]
my feeling is attention_masks cannot be "None" when it's non-transformer models as you did for the purpose of aligning transformer and non-transformer models.
